export const MANUFACTURING_PART_STATUSES = [
  "READY_FOR_BATCH",
  "BATCHED",
  "CUT_PENDING",
  "CUT_IN_PROGRESS",
  "CUT_COMPLETE",
  "EDGEBAND_PENDING",
  "EDGEBAND_IN_PROGRESS",
  "EDGEBAND_COMPLETE",
  "PACKAGING_PENDING",
  "PACKAGING_IN_PROGRESS",
  "PACKAGED",
  "HOLD",
  "ERROR"
] as const;

export const MANUFACTURING_BATCH_TYPES = ["CUT", "EDGEBAND", "PACKAGING"] as const;
export const MANUFACTURING_BATCH_STATUSES = ["OPEN", "IN_PROGRESS", "COMPLETE", "HOLD"] as const;
