export type BacklinkRecommendedTargetType =
  | "INTERIOR_DESIGN_BLOG"
  | "DIY_BLOG"
  | "HOME_IMPROVEMENT_SITE"
  | "CONTRACTOR_RESOURCE"
  | "FIREPLACE_DESIGN_SITE"
  | "LIFESTYLE_PINTEREST_CREATOR"
  | "LOCAL_PARTNER"
  | "PRESS_OR_FEATURE";

export type BacklinkTargetStatus = "PROSPECT" | "QUALIFIED" | "CONTACTED" | "WON" | "REJECTED" | "DEFERRED";
export type BacklinkAuthorityTier = "HIGH" | "MEDIUM" | "NICHE";

export type BacklinkTarget = {
  id: string;
  domain: string;
  siteName: string;
  targetType: BacklinkRecommendedTargetType;
  authorityTier: BacklinkAuthorityTier;
  topicCluster: string;
  fitNotes: string;
  status: BacklinkTargetStatus;
  preferredAssetTypes: string[];
  preferredCampaignKeys: string[];
  contactMethod: string | null;
  notes: string | null;
};

export const backlinkTargets: BacklinkTarget[] = [
  {
    id: "design-milk",
    domain: "design-milk.com",
    siteName: "Design Milk",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Strong fit for shelf styling roundups, fireplace shelving inspiration, and modern mantel idea resources.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Lead with design-resource framing and visual inspiration, not direct product promotion."
  },
  {
    id: "apartment-therapy",
    domain: "apartmenttherapy.com",
    siteName: "Apartment Therapy",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Best for broad shelf ideas, room-by-room styling, and accessible mantel design inspiration content.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Pitch guide-first, then use category pages as the commercial handoff."
  },
  {
    id: "the-spruce",
    domain: "thespruce.com",
    siteName: "The Spruce",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "materials",
    fitNotes: "Excellent for wood-selection, weight-planning, and evergreen floating shelf buying guidance.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["cabinet-shelf-measurement-resource-outreach", "floating-shelf-wood-material-outreach", "floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Material explainer and practical planning angles are stronger than a direct brand story."
  },
  {
    id: "decoist",
    domain: "decoist.com",
    siteName: "Decoist",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "design-ideas",
    fitNotes: "Good fit for fireplace styling, floating shelf living-room ideas, and modern mantel roundups.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Use the fireplace or styling angle first."
  },
  {
    id: "dwell",
    domain: "dwell.com",
    siteName: "Dwell",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "materials",
    fitNotes: "Strong editorial fit for white oak, minimalist shelf layouts, and architectural mantel references.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-wood-material-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Craftsmanship and material choices are the best hook."
  },
  {
    id: "house-beautiful",
    domain: "housebeautiful.com",
    siteName: "House Beautiful",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Useful for broad shelf ideas, room styling, and category-level inspiration references.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Use roundup-friendly copy and image-led examples."
  },
  {
    id: "mydomaine",
    domain: "mydomaine.com",
    siteName: "MyDomaine",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Good fit for resource-style shelf ideas and best-wood explainers with a polished design audience.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-shelf-wood-material-outreach"],
    contactMethod: null,
    notes: "Guide-first pitch keeps it editorial."
  },
  {
    id: "style-by-emily-henderson",
    domain: "stylebyemilyhenderson.com",
    siteName: "Style by Emily Henderson",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Excellent fit for styling guides, fireplace shelving resources, and mantel idea pages with strong visual hooks.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Styling and room-composition language works better than product copy."
  },
  {
    id: "remodelista",
    domain: "remodelista.com",
    siteName: "Remodelista",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "HIGH",
    topicCluster: "materials",
    fitNotes: "Great for material-led shelf and mantel references with an architectural or renovation angle.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-wood-material-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Material and craftsmanship framing is the right lead."
  },
  {
    id: "havenly",
    domain: "havenly.com",
    siteName: "Havenly",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "living-room-design",
    fitNotes: "Good target for living-room shelf ideas, styling tips, and consumer-friendly category references.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Room-use case and styling hooks are strongest."
  },
  {
    id: "ballard-designs-how-to-decorate",
    domain: "howtodecorate.com",
    siteName: "How to Decorate",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "design-ideas",
    fitNotes: "Better fit for shelf styling and mantel composition ideas than installation-heavy content.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Use idea-resource phrasing and visual examples."
  },
  {
    id: "the-identified-home",
    domain: "theidentifiedhome.com",
    siteName: "The Identite Home",
    targetType: "INTERIOR_DESIGN_BLOG",
    authorityTier: "NICHE",
    topicCluster: "styling-design",
    fitNotes: "Niche design audience that fits shelf styling guides and mantel inspiration references.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Smaller reach but strong topical fit."
  },

  {
    id: "family-handyman",
    domain: "familyhandyman.com",
    siteName: "Family Handyman",
    targetType: "DIY_BLOG",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Great fit for install guides, spacing/weight planning, and practical shelf resource content.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE"],
    preferredCampaignKeys: ["cabinet-shelf-measurement-resource-outreach", "floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Lead with how-to and troubleshooting language."
  },
  {
    id: "young-house-love",
    domain: "younghouselove.com",
    siteName: "Young House Love",
    targetType: "DIY_BLOG",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Good fit for approachable shelf planning guides and DIY-meets-design inspiration.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Use the install guide first, then styling guide as support."
  },
  {
    id: "ugly-duckling-house",
    domain: "uglyducklinghouse.com",
    siteName: "Ugly Duckling House",
    targetType: "DIY_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "installation",
    fitNotes: "Useful for practical floating-shelf install and built-in-adjacent planning resources.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Keep the pitch practical and build-led."
  },
  {
    id: "charleston-crafted",
    domain: "charlestoncrafted.com",
    siteName: "Charleston Crafted",
    targetType: "DIY_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "installation",
    fitNotes: "Good fit for weight-capacity, install, and shelf planning resources for homeowners.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Practical guide-first pitch."
  },
  {
    id: "build-basic",
    domain: "build-basic.com",
    siteName: "Build Basic",
    targetType: "DIY_BLOG",
    authorityTier: "NICHE",
    topicCluster: "installation",
    fitNotes: "Smaller but tightly aligned audience for installation resources and contractor-reference pages.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["cabinet-shelf-measurement-resource-outreach", "floating-shelf-installation-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Use build clarity, not design fluff."
  },
  {
    id: "h2obungalow",
    domain: "h2obungalow.com",
    siteName: "H2OBungalow",
    targetType: "DIY_BLOG",
    authorityTier: "NICHE",
    topicCluster: "bathroom-storage",
    fitNotes: "Good fit for bathroom shelf ideas, floating shelf planning, and smaller-space homeowner resources.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Bathroom and utility-space angles can differentiate the pitch."
  },
  {
    id: "ana-white",
    domain: "ana-white.com",
    siteName: "Ana White",
    targetType: "DIY_BLOG",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Strong fit for project planning, weight guidance, and contractor-grade floating shelf references.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Practical, step-based positioning works best."
  },
  {
    id: "the-created-home",
    domain: "thecreatedhome.com",
    siteName: "The Created Home",
    targetType: "DIY_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "installation",
    fitNotes: "Suitable for tutorial and planning-resource pitches tied to floating shelves and built-in projects.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["cabinet-shelf-measurement-resource-outreach", "floating-shelf-installation-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Guide-led pitch works best."
  },
  {
    id: "sawdust-2-stitches",
    domain: "sawdust2stitches.com",
    siteName: "Sawdust 2 Stitches",
    targetType: "DIY_BLOG",
    authorityTier: "NICHE",
    topicCluster: "installation",
    fitNotes: "Good fit for install and styling crossover where the audience wants both build help and finished-room ideas.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Lead with install guidance and use fireplace/living-room examples as support."
  },
  {
    id: "shanty-2-chic",
    domain: "shanty-2-chic.com",
    siteName: "Shanty 2 Chic",
    targetType: "DIY_BLOG",
    authorityTier: "MEDIUM",
    topicCluster: "installation",
    fitNotes: "Useful for practical how-to audiences that also respond to shelf styling and room makeover stories.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Keep the hook build-first with a design payoff."
  },
  {
    id: "houseful-of-handmade",
    domain: "housefulofhandmade.com",
    siteName: "Houseful of Handmade",
    targetType: "DIY_BLOG",
    authorityTier: "NICHE",
    topicCluster: "storage-design",
    fitNotes: "Best for practical shelf planning and storage/styling crossover content rather than product pages alone.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Storage and open-shelving use-case angles can help."
  },

  {
    id: "bob-vila",
    domain: "bobvila.com",
    siteName: "Bob Vila",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Strong fit for installation, weight-limit, and practical floating-shelf planning resources.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Lead with installation and planning resources."
  },
  {
    id: "this-old-house",
    domain: "thisoldhouse.com",
    siteName: "This Old House",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Excellent fit for contractor-grade planning guidance and installation-resource positioning.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Use credible planning language and avoid overly decorative framing."
  },
  {
    id: "renovated-faith",
    domain: "renovatedfaith.com",
    siteName: "Renovated Faith",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "MEDIUM",
    topicCluster: "materials",
    fitNotes: "Strong for wood-selection, finish-choice, and practical shelf refresh content.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-wood-material-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Wood and finish angle."
  },
  {
    id: "hunker",
    domain: "hunker.com",
    siteName: "Hunker",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Good fit for design-resource and practical shelf/mantel planning content with broad home-improvement appeal.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Broad home-improvement audience with design overlap."
  },
  {
    id: "bhg",
    domain: "bhg.com",
    siteName: "Better Homes & Gardens",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "HIGH",
    topicCluster: "design-ideas",
    fitNotes: "Good for broad inspiration, shelf styling, and mantel roundup content that still supports category authority.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Guide-first pitch with category pages as follow-through."
  },
  {
    id: "real-homes",
    domain: "realhomes.com",
    siteName: "Real Homes",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "MEDIUM",
    topicCluster: "styling-design",
    fitNotes: "Good fit for living-room shelf ideas, mantel planning, and accessible buying guidance.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Use planning and inspiration together."
  },
  {
    id: "homedit",
    domain: "homedit.com",
    siteName: "Homedit",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "MEDIUM",
    topicCluster: "design-ideas",
    fitNotes: "Useful for styling-led guide outreach and category references across shelves and mantels.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Guide or category pages fit better than niche long-tail variants."
  },
  {
    id: "love-property",
    domain: "loveproperty.com",
    siteName: "Love Property",
    targetType: "HOME_IMPROVEMENT_SITE",
    authorityTier: "MEDIUM",
    topicCluster: "design-ideas",
    fitNotes: "Good for room inspiration and fireplace feature roundups with commercial category support.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Use visual and inspiration-led hooks."
  },

  {
    id: "fireplace-universe",
    domain: "fireplaceuniverse.com",
    siteName: "Fireplace Universe",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "NICHE",
    topicCluster: "fireplace",
    fitNotes: "Direct fit for floating mantel design ideas and fireplace-specific product/category references.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Mantel design angle is strongest."
  },
  {
    id: "decorative-ceiling-tiles-fireplace",
    domain: "decorativeceilingtiles.net",
    siteName: "Decorative Ceiling Tiles / Fireplace Mantels",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "NICHE",
    topicCluster: "fireplace",
    fitNotes: "Good fit for mantel-style, fireplace-wall, and feature-wall reference content.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Use fireplace-style resource framing."
  },
  {
    id: "heatilator-blog",
    domain: "heatilator.com",
    siteName: "Heatilator",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "MEDIUM",
    topicCluster: "fireplace",
    fitNotes: "Good fit for fireplace planning and mantel design resources if framed educationally.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Use design-resource angle, not direct product sell."
  },
  {
    id: "heatnglo-blog",
    domain: "heatnglo.com",
    siteName: "Heat & Glo",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "MEDIUM",
    topicCluster: "fireplace",
    fitNotes: "Mantel design guidance and fireplace composition references fit here.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Fireplace-specific audience."
  },
  {
    id: "brick-anew",
    domain: "brick-anew.com",
    siteName: "Brick-Anew",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "NICHE",
    topicCluster: "fireplace",
    fitNotes: "Useful for fireplace makeover and mantel update content where a design guide is a natural citation.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Design refresh angle."
  },
  {
    id: "elegant-fireside",
    domain: "elegantfireside.com",
    siteName: "Elegant Fireside",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "NICHE",
    topicCluster: "fireplace",
    fitNotes: "Category and flagship mantel references fit better than long-tail variants for this audience.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["flagship-product-category-authority-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Commercial authority angle."
  },
  {
    id: "northline-express",
    domain: "northlineexpress.com",
    siteName: "Northline Express",
    targetType: "FIREPLACE_DESIGN_SITE",
    authorityTier: "NICHE",
    topicCluster: "fireplace",
    fitNotes: "Good fit for fireplace category references and mantel planning resources with a product-aware audience.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT", "GUIDE"],
    preferredCampaignKeys: ["floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Category pages usually pitch better than very specific variants."
  },

  {
    id: "fine-homebuilding",
    domain: "finehomebuilding.com",
    siteName: "Fine Homebuilding",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Best fit for contractor-reference pages and installation-resource pitches with real technical value.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Use contractor-reference pitch angle."
  },
  {
    id: "journal-of-light-construction",
    domain: "jlconline.com",
    siteName: "JLC Online",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "HIGH",
    topicCluster: "installation",
    fitNotes: "Suitable for shelf install guidance and contractor-grade product references.",
    status: "QUALIFIED",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Technical clarity matters."
  },
  {
    id: "pro-builder",
    domain: "probuilder.com",
    siteName: "Pro Builder",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "MEDIUM",
    topicCluster: "commercial-authority",
    fitNotes: "Good fit for category authority and product reference placements with a trade audience.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Trade-facing product/category angle."
  },
  {
    id: "builderonline",
    domain: "builderonline.com",
    siteName: "Builder Online",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "MEDIUM",
    topicCluster: "commercial-authority",
    fitNotes: "Useful for flagship product and category authority outreach, not broad lifestyle-oriented guide outreach.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Commercial authority placement."
  },
  {
    id: "contractor-talk",
    domain: "contractortalk.com",
    siteName: "Contractor Talk",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "NICHE",
    topicCluster: "installation",
    fitNotes: "Niche fit for contractor-reference and installation-resource pages where practical guidance matters.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-installation-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Practical and trade-led."
  },
  {
    id: "remodeling-magazine",
    domain: "remodeling.hw.net",
    siteName: "Remodeling Magazine",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "MEDIUM",
    topicCluster: "commercial-authority",
    fitNotes: "Good for authority and category reference when paired with product quality and project-fit positioning.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Commercial authority and build-quality angle."
  },
  {
    id: "architectural-woodwork-institute",
    domain: "awinet.org",
    siteName: "Architectural Woodwork Institute",
    targetType: "CONTRACTOR_RESOURCE",
    authorityTier: "NICHE",
    topicCluster: "materials",
    fitNotes: "Good fit for craftsmanship and wood-quality references when framed as material-selection guidance.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-wood-material-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Material quality and fabrication angle."
  },

  {
    id: "pinterest-creator-emily-henderson",
    domain: "stylebyemilyhenderson.com",
    siteName: "Emily Henderson / Style Content",
    targetType: "LIFESTYLE_PINTEREST_CREATOR",
    authorityTier: "HIGH",
    topicCluster: "styling-design",
    fitNotes: "Useful for shelf styling and fireplace inspiration assets that can travel well on Pinterest.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Use visual idea-resource language and keep the destination guide-led."
  },
  {
    id: "pinterest-creator-jungalow",
    domain: "jungalow.com",
    siteName: "Jungalow",
    targetType: "LIFESTYLE_PINTEREST_CREATOR",
    authorityTier: "MEDIUM",
    topicCluster: "styling-design",
    fitNotes: "Better fit for styled shelf inspiration and design-heavy category references than contractor pages.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach"],
    contactMethod: null,
    notes: "Lead with inspiration and room styling."
  },
  {
    id: "pinterest-creator-coco-kelley",
    domain: "cocolapinedesign.com",
    siteName: "Coco Lapine Design",
    targetType: "LIFESTYLE_PINTEREST_CREATOR",
    authorityTier: "NICHE",
    topicCluster: "modern-design",
    fitNotes: "A fit for white oak shelf and mantel inspiration where the visual story is minimal and elevated.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-wood-material-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "White oak and modern mantel angles fit best."
  },
  {
    id: "pinterest-creator-chris-loves-julia",
    domain: "chrislovesjulia.com",
    siteName: "Chris Loves Julia",
    targetType: "LIFESTYLE_PINTEREST_CREATOR",
    authorityTier: "HIGH",
    topicCluster: "design-ideas",
    fitNotes: "Good fit for room makeover, shelf styling, and mantel inspiration content with strong Pinterest distribution potential.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Use inspiration and makeover framing."
  },
  {
    id: "pinterest-creator-lone-fox",
    domain: "thelonelyfox.com",
    siteName: "Lone Fox",
    targetType: "LIFESTYLE_PINTEREST_CREATOR",
    authorityTier: "MEDIUM",
    topicCluster: "styling-design",
    fitNotes: "Useful for shelf and mantel styling content with strong visual and tutorial crossover.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "PROGRAMMATIC_VARIANT"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Pair styling guide assets with fireplace visuals."
  },
  {
    id: "pinterest-creator-the-blondielocks",
    domain: "theblondielocks.com",
    siteName: "The Blondielocks",
    targetType: "LIFESTYLE_PINTEREST_CREATOR",
    authorityTier: "NICHE",
    topicCluster: "diy-styling",
    fitNotes: "Good for home styling and shelf refresh content where a guide can drive the editorial value.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "DIY-plus-design hybrid audience."
  },

  {
    id: "local-partner-hammer-and-hand",
    domain: "hammerandhand.com",
    siteName: "Hammer & Hand",
    targetType: "LOCAL_PARTNER",
    authorityTier: "NICHE",
    topicCluster: "local-trade",
    fitNotes: "Good fit for relationship-based product/category references and locally relevant installation resources.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["flagship-product-category-authority-outreach", "floating-shelf-installation-outreach"],
    contactMethod: null,
    notes: "Use partner/resource framing, not editorial outreach language."
  },
  {
    id: "local-partner-board-and-vellum",
    domain: "boardandvellum.com",
    siteName: "Board & Vellum",
    targetType: "LOCAL_PARTNER",
    authorityTier: "NICHE",
    topicCluster: "local-design",
    fitNotes: "Strong fit for shelf styling and mantel inspiration pages when building local design relationships.",
    status: "PROSPECT",
    preferredAssetTypes: ["GUIDE", "COMMERCIAL_CATEGORY"],
    preferredCampaignKeys: ["floating-shelf-design-outreach", "floating-mantel-design-outreach"],
    contactMethod: null,
    notes: "Design-studio partner angle."
  },
  {
    id: "local-partner-jackson-design-remodeling",
    domain: "jacksondesignandremodeling.com",
    siteName: "Jackson Design and Remodeling",
    targetType: "LOCAL_PARTNER",
    authorityTier: "NICHE",
    topicCluster: "local-fireplace",
    fitNotes: "Best fit for mantel category, flagship mantel PDP, and fireplace design guide references.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT", "GUIDE"],
    preferredCampaignKeys: ["floating-mantel-design-outreach", "flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Fireplace showroom partnerships should lead with mantel authority pages."
  },
  {
    id: "local-partner-gaspars",
    domain: "gaspars.com",
    siteName: "Neil Kelly / Gaspar's Design-Build",
    targetType: "LOCAL_PARTNER",
    authorityTier: "NICHE",
    topicCluster: "local-remodel",
    fitNotes: "Useful for category authority and flagship product references tied to contractor and remodel projects.",
    status: "PROSPECT",
    preferredAssetTypes: ["COMMERCIAL_CATEGORY", "COMMERCIAL_PRODUCT"],
    preferredCampaignKeys: ["flagship-product-category-authority-outreach"],
    contactMethod: null,
    notes: "Relationship-led partner outreach."
  }
];
