export const SALES_ORDER_SOURCE_TYPES = ["MANUAL", "AMAZON", "CSV", "CONFIGURATOR"] as const;
export const SALES_ORDER_STATUSES = ["DRAFT", "READY", "HOLD", "ERROR", "CONVERTED"] as const;
export const SALES_ORDER_ITEM_NORMALIZATION_STATUSES = ["PENDING", "NORMALIZED", "HOLD", "ERROR"] as const;
export const SALES_ORDER_ITEM_PRICING_STATUSES = ["PENDING", "PRICED", "HOLD", "ERROR"] as const;
export const SHELF_JOB_STATUSES = ["READY", "HOLD", "ERROR", "CONVERTED_TO_MANUFACTURING"] as const;
export const MANUFACTURING_PACKET_SOURCE_TYPES = ["SALES_ORDER", "SHELF_JOB"] as const;

